### ISSUE TITLE
Wiki erweitern

### ISSUE THREAD

**Issue by julioa16** [julioa16/GitHub#5]
Hinzufügen folgender Begriffe für die Suchleiste, die nützlich sein könnten:
(Wörter in Anführungszeichen werden ersetzt durch jeweiligen gesuchten Begriff)
- [x] "reponame" in:name
- [x] filename:"filename"

Außerdem hat aus versehen den Eintrag über Issues und Pull Requests (PR) gelöscht.
Fülle die Seite neu und beschreibe für was man Issues und PR benötigt.

**Comment by 10FI1** [comment]
Meine Aufgabe. :+1:
